app,counter, runnable, thread classes implemented
semyonich/multithread pull request #1
Opened 2021-02-22 16:48 UTC by semyonich

2021-02-22 21:58 UTC, Ketch92 approved these changes

2021-02-22 21:58 UTC, Ketch92 commented on src/main/java/com/multithread/RunnableClass.java
> +    }
it does seems you don't need to override this

2021-02-22 21:58 UTC, Ketch92 commented on src/main/java/com/multithread/Counter.java
> +}
is it possible to solve it with a bit less amount of code?

2021-02-23 06:25 UTC, semyonich commented on src/main/java/com/multithread/RunnableClass.java
> +    }
its not overriding, in Runnable we have no start(), so we need to implement it

2021-02-23 06:28 UTC, semyonich commented on src/main/java/com/multithread/Counter.java
> +}
setter removed? we dont use it

2021-02-23 07:44 UTC, Sofasmile requested changes

2021-02-23 07:44 UTC, Sofasmile commented on src/main/java/com/multithread/Application.java
> +        Counter counter = new Counter(COUNTER_START);
```suggestion
        Counter counter = new Counter();
```
0 це дефолтне значення для числових типів

2021-02-23 07:44 UTC, Sofasmile commented on src/main/java/com/multithread/RunnableClass.java
> +    }
це краще винести в main метод

2021-02-23 07:49 UTC, semyonich commented on src/main/java/com/multithread/Application.java
> +        Counter counter = new Counter(COUNTER_START);
done

2021-02-23 07:49 UTC, semyonich commented on src/main/java/com/multithread/RunnableClass.java
> +    }
done

2021-02-23 09:45 UTC, Sofasmile approved these changes

2021-02-23 10:08 UTC, merged