ExecutorServiceSum, ForkJoinSum, MyCallable, Util classes and Tests i…
semyonich/multithread pull request #2
Opened 2021-02-23 20:02 UTC by semyonich

…mplemented

2021-02-24 06:37 UTC, NikolayFatkullin approved these changes

2021-02-24 11:13 UTC, RomanDubovskyi requested changes

2021-02-24 11:13 UTC, RomanDubovskyi commented on src/main/java/com/multithread/ExecutorServiceSum.java
> +        List<MyCallable> callableTasks = new ArrayList<>();
```suggestion
        List<Callable> callableTasks = new ArrayList<>();
```
use abstraction where possible

2021-02-24 11:13 UTC, RomanDubovskyi commented on src/main/java/com/multithread/ForkJoinSum.java
> +            return processing(intList);
```suggestion
        } 
            return processing(intList);
```
we don't need else after return

2021-02-24 11:13 UTC, RomanDubovskyi commented on src/main/java/com/multithread/ForkJoinSum.java
> +    private Long processing(List<Integer> list) {
```suggestion
    private Long process(List<Integer> list) {
```

2021-02-24 11:13 UTC, RomanDubovskyi commented on src/main/java/com/multithread/MyCallable.java
> +public class MyCallable implements Callable<Long> {
```suggestion
public class ListSumCulculator implements Callable<Long> {
```

2021-02-24 11:13 UTC, RomanDubovskyi commented on src/main/java/com/multithread/Util.java
> +public class Util {
```suggestion
public class ListProducer {
```

2021-02-24 11:13 UTC, RomanDubovskyi commented on src/test/java/ExecutorServiceSumTest.java
> +    public static void beforeAll() {
add more than one test case, this of different scenarios

2021-02-24 19:14 UTC, semyonich commented on src/main/java/com/multithread/ExecutorServiceSum.java
> +        List<MyCallable> callableTasks = new ArrayList<>();
done

2021-02-24 19:14 UTC, semyonich commented on src/main/java/com/multithread/ForkJoinSum.java
> +            return processing(intList);
done

2021-02-24 19:14 UTC, semyonich commented on src/main/java/com/multithread/ForkJoinSum.java
> +    private Long processing(List<Integer> list) {
done

2021-02-24 19:14 UTC, semyonich commented on src/main/java/com/multithread/MyCallable.java
> +public class MyCallable implements Callable<Long> {
done

2021-02-24 19:15 UTC, semyonich commented on src/main/java/com/multithread/Util.java
> +public class Util {
done

2021-02-24 20:09 UTC, semyonich commented on src/test/java/ExecutorServiceSumTest.java
> +    public static void beforeAll() {
done

2021-02-25 07:30 UTC, RomanDubovskyi approved these changes
good job

2021-02-25 08:04 UTC, merged